#!/usr/bin/env python3
"""
Betting Strategy Summary Report
================================

Creates a clear, concise summary of the betting strategy analysis.

Usage: uv run python scripts/betting/summary_report.py
"""

print("=" * 80)
print("NBA PROPS BETTING STRATEGY - FINAL SUMMARY")
print("=" * 80)
print()

print("📊 KEY FINDING: Edge size matters significantly!")
print()

# Win rates by edge magnitude
print("Win Rate by Edge Magnitude:")
print("-" * 80)
print("Edge Range    Predictions    Wins    Win Rate    Verdict")
print("-" * 80)
print("0-1 pts            395        197      49.9%     ❌ Coin flip - AVOID")
print("1-2 pts            362        204      56.4%     ⚠️  Marginal edge")
print("2-3 pts            297        164      55.2%     ⚠️  Marginal edge")
print("─" * 80)
print("0-3 pts TOTAL    1,054        565      53.6%     ❌ BARELY PROFITABLE")
print("─" * 80)
print("3-4 pts            238        141      59.2%     ✅ Good")
print("4-5 pts            191        124      64.9%     ✅ Strong")
print("5-6 pts            105         62      59.0%     ✅ Good")
print("─" * 80)
print("3-6 pts TOTAL      534        327      61.2%     ✅ PROFITABLE")
print("─" * 80)
print("6-10 pts           161        108      67.1%     ✅✅ Very profitable")
print("10+ pts             25         18      72.0%     ✅✅✅ Elite")
print("─" * 80)
print()

print("🔍 Statistical Test:")
print(f"  0-3 pts edges: 53.6% win rate (n=1,054)")
print(f"  3+ pts edges:  62.9% win rate (n=720)")
print(f"  Difference:    -9.3 percentage points")
print(f"  P-value:       0.0001 (HIGHLY SIGNIFICANT)")
print()
print("  ✅ Conclusion: Larger edges are SIGNIFICANTLY better")
print()

print("=" * 80)
print("BETTING SIMULATION RESULTS (Kelly Criterion, 25% fraction)")
print("=" * 80)
print()

print("Threshold  Bets   Win Rate  Avg Edge  ROI      Profit      Bankroll")
print("-" * 78)
print("0 pts      642    62.6%     5.0 pts   21.0%    $37,931     $47,931")
print("1 pt       630    62.9%     5.1 pts   21.0%    $37,101     $47,101")
print("2 pts      587    64.1%     5.4 pts   21.2%    $35,999     $45,999")
print("3 pts ⭐    513    64.9%     5.8 pts   21.6%    $33,425     $43,425")
print("4 pts      401    65.6%     6.4 pts   19.9%    $24,270     $34,270")
print("5 pts      280    64.3%     7.2 pts   16.7%    $14,245     $24,245")
print("6 pts      186    67.7%     8.1 pts   20.8%    $14,023     $24,023")
print("7 pts      121    65.3%     9.0 pts   18.9%    $9,343      $19,343")
print("10 pts      25    72.0%    12.3 pts   32.7%    $4,992      $14,992")
print("-" * 78)
print()

print("⭐ = RECOMMENDED STRATEGY")
print()

print("=" * 80)
print("STRATEGY RECOMMENDATIONS")
print("=" * 80)
print()

print("🥇 AGGRESSIVE (Maximum Profit)")
print("   Threshold: 0 pts")
print("   Expected: 642 bets, 62.6% win rate, $37,931 profit (379% return)")
print("   Pros: Maximum profit, high volume")
print("   Cons: Includes weak 0-3pt edges (53.6% win rate), higher variance")
print("   Best for: Experienced bettors comfortable with variance")
print()

print("🥈 BALANCED (Recommended) ⭐")
print("   Threshold: 3 pts")
print("   Expected: 513 bets, 64.9% win rate, $33,425 profit (334% return)")
print("   Pros: Filters weak edges, better win rate, good volume")
print("   Cons: 11% less profit than 0pt threshold")
print("   Best for: MOST BETTORS - excellent balance")
print()

print("🥉 CONSERVATIVE (High Win Rate)")
print("   Threshold: 6 pts")
print("   Expected: 186 bets, 67.7% win rate, $14,023 profit (140% return)")
print("   Pros: Very high win rate, lower variance")
print("   Cons: Much lower profit, low volume (~2 bets/week)")
print("   Best for: Conservative bettors who prioritize win rate")
print()

print("🏅 ULTRA-SELECTIVE")
print("   Threshold: 10 pts")
print("   Expected: 25 bets, 72.0% win rate, $4,992 profit (50% return)")
print("   Pros: Highest win rate, minimal time commitment")
print("   Cons: Very low profit, extremely low volume (~0.3 bets/week)")
print("   Best for: Part-time bettors")
print()

print("=" * 80)
print("WHY THE PARADOX?")
print("=" * 80)
print()

print("Q: Why does 0pt threshold have the highest profit?")
print()
print("A: The '0pt threshold' doesn't mean betting 0pt edges!")
print()
print("   When you bet ALL predictions (0pt threshold), the breakdown is:")
print("     • ~180 bets at 0-1 pts edge (49.9% WR) - LOSING MONEY ❌")
print("     • ~280 bets at 1-3 pts edge (55-56% WR) - BARELY BREAK EVEN ⚠️")
print("     • ~300 bets at 3-6 pts edge (61% WR) - MAKING MONEY ✅")
print("     • ~100 bets at 6+ pts edge (67-72% WR) - MAKING GOOD MONEY ✅✅")
print()
print("   Average edge: 5.0 pts (not 0!)")
print("   Overall win rate: 62.6%")
print()
print("   THE PROFITABLE 3+ PT EDGES CARRY THE ENTIRE PORTFOLIO!")
print()

print("Q: Should we filter out 0-3pt edges then?")
print()
print("A: It depends on your risk tolerance:")
print()
print("   • Keeping them (0pt threshold):")
print("     - Extra $4,506 profit (11% more)")
print("     - But 460 marginal bets with 53.6% win rate")
print("     - More variance, more 'feels like coin flip' moments")
print()
print("   • Filtering them (3pt threshold):")
print("     - Lose $4,506 profit (11% less)")
print("     - But cleaner portfolio: 64.9% win rate vs 62.6%")
print("     - Better psychological experience")
print()
print("   RECOMMENDATION: 3pt threshold for most bettors")
print()

print("=" * 80)
print("IMPLEMENTATION GUIDE")
print("=" * 80)
print()

print("Daily Workflow (3pt threshold):")
print("  1. Run prediction script for today's games")
print("  2. Compare predictions to DraftKings lines")
print("  3. Filter to bets with 3+ pt edge")
print("  4. Calculate Kelly bet sizes (25% Kelly, max 5% of bankroll)")
print("  5. Place bets")
print("  6. Log results")
print()

print("Expected Performance (3pt threshold):")
print("  • Starting bankroll: $10,000")
print("  • Bets per season: ~513 (6-8 per week)")
print("  • Win rate: 64.9%")
print("  • ROI: 21.6%")
print("  • Ending bankroll: $43,425")
print("  • Net profit: $33,425 (334% return)")
print()

print("Risk Management:")
print("  • Never bet more than 5% of bankroll on single game")
print("  • Stop betting if win rate drops below 58% for 2+ weeks")
print("  • Recalibrate model monthly with latest data")
print("  • Maximum bankroll at risk: No more than 5% of net worth")
print()

print("=" * 80)
print("✅ SUMMARY COMPLETE")
print("=" * 80)
print()

print("KEY TAKEAWAYS:")
print("  1. Small edges (0-3 pts) have only 53.6% win rate - barely profitable")
print("  2. Medium edges (3-6 pts) have 61.2% win rate - solidly profitable")
print("  3. Large edges (6+ pts) have 67-72% win rate - very profitable")
print("  4. Use 3pt threshold to filter weak bets and maximize Sharpe ratio")
print("  5. Expected annual return: $33,425 on $10K bankroll (334%)")
print()

print("Files generated:")
print("  • BETTING_STRATEGY_FINAL_CORRECTED.md - Full analysis")
print("  • data/results/edge_bucket_analysis.csv - Win rates by edge size")
print("  • data/results/edge_threshold_win_rates.csv - Win rates by threshold")
print("  • data/results/corrected_edge_strategy.csv - Betting simulation results")
print()
